server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ea89d7fd7c7a45059433c9ecdb257cfb
      model-name: deepseek-chat
      log-responses: false
      log-requests: false
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ea89d7fd7c7a45059433c9ecdb257cfb
      model-name: deepseek-chat
      log-responses: false
      log-requests: false

spring:
  application:
    name:
      VirtualAIBox

  virtual-clock:
    # 时间刻度
    tick: 0
    # 时间步长
    interval: 30
    # 元时间：虚拟时钟的起始时间
    meta-instant: 2026-06-03T00:00:00+08:00

